### PR TITLE
Added react-toastify for invalid ClippyID notification

### PR DESCRIPTION
**Pull request by satmm**
# Pull Request

### Title
Added react-toastify for invalid ClippyID notification

### Description
This PR adds a notification using react-toastify to inform users when an invalid ClippyID is entered. If the ClippyID does not exist, a toast message will appear with the text "This ClippyID does not exist!".

### Related Issues
Fixes #25

### Changes Made
- Integrated react-toastify into the application.
- Added toast notification for invalid ClippyID in the `Home` component.

### Checklist
- [x] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### Screenshots (if applicable)
Screenshot (251)

### Additional Notes
Please review the changes and let me know if any adjustments are needed.

### CODE REVIEW

**Comment by subinoybiswas** [comment]
Clippy IDs are not being generated in the preview deploymeny

**Comment by satmm** [comment]
> Clippy IDs are not being generated in the preview deploymeny

@subinoybiswas  I have created a new pull request ...Could you please review and deploy it? Let me know if you encounter any deployment errors. #1

**Comment by subinoybiswas** [comment]
Caught the issue, 
`const uri = process.env.MONGODB_URI;` should be
`const uri = process.env.MONGO_URI;`

**Comment by satmm** [comment]
I have 

> Caught the issue, `const uri = process.env.MONGODB_URI;` should be `const uri = process.env.MONGO_URI;`

@subinoybiswas I have fixed that could you please deploy it again !

**Pull request merged**
