### PR TITLE
changes

### PR DESCRIPTION
**Pull request by 05hiteshbansal**
# Pull Request

### Title
successfully completed the task

### Description
I have added google icons to the return button

### Related Issues
issue #55

### Checklist 

- [x ] I have tested the changes locally
- [ x] Documentation has been updated (if necessary)
- [ x] Changes are backward-compatible

### Screenshots (if applicable)

image

### CODE REVIEW

**Comment by 05hiteshbansal** [comment]
Please review my changes and also add a Gssoc level to the PR

**Comment by subinoybiswas** [comment]
When the page loads, it shows the text arrow_back and then loads the icon, fix that

**Comment by 05hiteshbansal** [comment]
changes done please review my changes

**Comment by 05hiteshbansal** [comment]
please review my changes

**Pull request merged**
