### PR TITLE
[Fixes]: Adding an error message for non-existent clippy id #20

### PR DESCRIPTION
**Pull request by aryansharma220**
Fixes: #20 

### Title
Added toast message for invalid clippy Id

### Description
Added a route to check for if the given clippy is valid or not, if invalid a toast will appear else it will continue to fetch the message

### Checklist 

- [X] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [X] Changes are backward-compatible

### Screenshots (if applicable)
image

### Additional Notes

Footer

### CODE REVIEW

**Comment by subinoybiswas** [comment]
Getting Build Errors
image

**Comment by aryansharma220** [comment]
@subinoybiswas I am getting the same issue for createClippy route also. Can you give me some idea how to solve it.

**Comment by aryansharma220** [comment]
> @subinoybiswas I am getting the same issue for createClippy route also. Can you give me some idea how to solve it.

It is saying there is some issue with the mongodb uri as connection string but the uri is completely working

**Comment by subinoybiswas** [comment]
Not quite sure, make a temp mongodb in local and test
Use this for reference
image

**Pull request closed without merging**
